//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaceWCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSEACEappEntities : DbContext
    {
        public dbSEACEappEntities()
            : base("name=dbSEACEappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<forumCategory> forumCategories { get; set; }
        public virtual DbSet<forumPost> forumPosts { get; set; }
        public virtual DbSet<forumSubcategory> forumSubcategories { get; set; }
        public virtual DbSet<forumVote> forumVotes { get; set; }
        public virtual DbSet<person> persons { get; set; }
    }
}
