//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.forumPosts = new HashSet<forumPost>();
            this.forumVotes = new HashSet<forumVote>();
        }
    
        public long idPerson { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public byte[] picture { get; set; }
        public string email { get; set; }
        public Nullable<bool> active { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
    
        public virtual ICollection<forumPost> forumPosts { get; set; }
        public virtual ICollection<forumVote> forumVotes { get; set; }
    }
}
