//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DroidSeace.SeaceWCF {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPersonQuery", Namespace="http://tempuri.org/")]
    public partial class ServiceApp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPersonaXnombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPersonasOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarPersonaPorIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceApp() {
            this.Url = "http://gsaico-001-site1.btempurl.com/SeaceService/ServiceApp.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertarPersonaCompletedEventHandler InsertarPersonaCompleted;
        
        /// <remarks/>
        public event ActualizarPersonaCompletedEventHandler ActualizarPersonaCompleted;
        
        /// <remarks/>
        public event EliminarPersonaCompletedEventHandler EliminarPersonaCompleted;
        
        /// <remarks/>
        public event ListarPersonaXnombreCompletedEventHandler ListarPersonaXnombreCompleted;
        
        /// <remarks/>
        public event ListarPersonasCompletedEventHandler ListarPersonasCompleted;
        
        /// <remarks/>
        public event BuscarPersonaPorIDCompletedEventHandler BuscarPersonaPorIDCompleted;
        
        /// <remarks/>
        public event VerificarPasswordCompletedEventHandler VerificarPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonQuery/InsertarPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarPersona([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] personDTO dto, out long InsertarPersonaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool InsertarPersonaResultSpecified) {
            object[] results = this.Invoke("InsertarPersona", new object[] {
                        dto});
            InsertarPersonaResult = ((long)(results[0]));
            InsertarPersonaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void InsertarPersonaAsync(personDTO dto) {
            this.InsertarPersonaAsync(dto, null);
        }
        
        /// <remarks/>
        public void InsertarPersonaAsync(personDTO dto, object userState) {
            if ((this.InsertarPersonaOperationCompleted == null)) {
                this.InsertarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarPersonaOperationCompleted);
            }
            this.InvokeAsync("InsertarPersona", new object[] {
                        dto}, this.InsertarPersonaOperationCompleted, userState);
        }
        
        private void OnInsertarPersonaOperationCompleted(object arg) {
            if ((this.InsertarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarPersonaCompleted(this, new InsertarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonQuery/ActualizarPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarPersona([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] personDTO dto, out bool ActualizarPersonaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ActualizarPersonaResultSpecified) {
            object[] results = this.Invoke("ActualizarPersona", new object[] {
                        dto});
            ActualizarPersonaResult = ((bool)(results[0]));
            ActualizarPersonaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ActualizarPersonaAsync(personDTO dto) {
            this.ActualizarPersonaAsync(dto, null);
        }
        
        /// <remarks/>
        public void ActualizarPersonaAsync(personDTO dto, object userState) {
            if ((this.ActualizarPersonaOperationCompleted == null)) {
                this.ActualizarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarPersonaOperationCompleted);
            }
            this.InvokeAsync("ActualizarPersona", new object[] {
                        dto}, this.ActualizarPersonaOperationCompleted, userState);
        }
        
        private void OnActualizarPersonaOperationCompleted(object arg) {
            if ((this.ActualizarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarPersonaCompleted(this, new ActualizarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonQuery/EliminarPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarPersona(long idperson, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idpersonSpecified, out bool EliminarPersonaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool EliminarPersonaResultSpecified) {
            object[] results = this.Invoke("EliminarPersona", new object[] {
                        idperson,
                        idpersonSpecified});
            EliminarPersonaResult = ((bool)(results[0]));
            EliminarPersonaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void EliminarPersonaAsync(long idperson, bool idpersonSpecified) {
            this.EliminarPersonaAsync(idperson, idpersonSpecified, null);
        }
        
        /// <remarks/>
        public void EliminarPersonaAsync(long idperson, bool idpersonSpecified, object userState) {
            if ((this.EliminarPersonaOperationCompleted == null)) {
                this.EliminarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarPersonaOperationCompleted);
            }
            this.InvokeAsync("EliminarPersona", new object[] {
                        idperson,
                        idpersonSpecified}, this.EliminarPersonaOperationCompleted, userState);
        }
        
        private void OnEliminarPersonaOperationCompleted(object arg) {
            if ((this.EliminarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarPersonaCompleted(this, new EliminarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonQuery/ListarPersonaXnombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SeaceWCF.Dtos")]
        public personDTO[] ListarPersonaXnombre([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nombrespersona) {
            object[] results = this.Invoke("ListarPersonaXnombre", new object[] {
                        nombrespersona});
            return ((personDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPersonaXnombreAsync(string nombrespersona) {
            this.ListarPersonaXnombreAsync(nombrespersona, null);
        }
        
        /// <remarks/>
        public void ListarPersonaXnombreAsync(string nombrespersona, object userState) {
            if ((this.ListarPersonaXnombreOperationCompleted == null)) {
                this.ListarPersonaXnombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPersonaXnombreOperationCompleted);
            }
            this.InvokeAsync("ListarPersonaXnombre", new object[] {
                        nombrespersona}, this.ListarPersonaXnombreOperationCompleted, userState);
        }
        
        private void OnListarPersonaXnombreOperationCompleted(object arg) {
            if ((this.ListarPersonaXnombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPersonaXnombreCompleted(this, new ListarPersonaXnombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonQuery/ListarPersonas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SeaceWCF.Dtos")]
        public personDTO[] ListarPersonas() {
            object[] results = this.Invoke("ListarPersonas", new object[0]);
            return ((personDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPersonasAsync() {
            this.ListarPersonasAsync(null);
        }
        
        /// <remarks/>
        public void ListarPersonasAsync(object userState) {
            if ((this.ListarPersonasOperationCompleted == null)) {
                this.ListarPersonasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPersonasOperationCompleted);
            }
            this.InvokeAsync("ListarPersonas", new object[0], this.ListarPersonasOperationCompleted, userState);
        }
        
        private void OnListarPersonasOperationCompleted(object arg) {
            if ((this.ListarPersonasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPersonasCompleted(this, new ListarPersonasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonQuery/BuscarPersonaPorID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public personDTO BuscarPersonaPorID(long idperson, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idpersonSpecified) {
            object[] results = this.Invoke("BuscarPersonaPorID", new object[] {
                        idperson,
                        idpersonSpecified});
            return ((personDTO)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarPersonaPorIDAsync(long idperson, bool idpersonSpecified) {
            this.BuscarPersonaPorIDAsync(idperson, idpersonSpecified, null);
        }
        
        /// <remarks/>
        public void BuscarPersonaPorIDAsync(long idperson, bool idpersonSpecified, object userState) {
            if ((this.BuscarPersonaPorIDOperationCompleted == null)) {
                this.BuscarPersonaPorIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarPersonaPorIDOperationCompleted);
            }
            this.InvokeAsync("BuscarPersonaPorID", new object[] {
                        idperson,
                        idpersonSpecified}, this.BuscarPersonaPorIDOperationCompleted, userState);
        }
        
        private void OnBuscarPersonaPorIDOperationCompleted(object arg) {
            if ((this.BuscarPersonaPorIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarPersonaPorIDCompleted(this, new BuscarPersonaPorIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonQuery/VerificarPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void VerificarPassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] personDTO dto, out bool VerificarPasswordResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool VerificarPasswordResultSpecified) {
            object[] results = this.Invoke("VerificarPassword", new object[] {
                        dto});
            VerificarPasswordResult = ((bool)(results[0]));
            VerificarPasswordResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void VerificarPasswordAsync(personDTO dto) {
            this.VerificarPasswordAsync(dto, null);
        }
        
        /// <remarks/>
        public void VerificarPasswordAsync(personDTO dto, object userState) {
            if ((this.VerificarPasswordOperationCompleted == null)) {
                this.VerificarPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarPasswordOperationCompleted);
            }
            this.InvokeAsync("VerificarPassword", new object[] {
                        dto}, this.VerificarPasswordOperationCompleted, userState);
        }
        
        private void OnVerificarPasswordOperationCompleted(object arg) {
            if ((this.VerificarPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarPasswordCompleted(this, new VerificarPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SeaceWCF.Dtos")]
    public partial class personDTO {
        
        private System.Nullable<bool> activeField;
        
        private bool activeFieldSpecified;
        
        private string emailField;
        
        private string first_nameField;
        
        private forumPostDTO[] forumPostsField;
        
        private forumVoteDTO[] forumVotesField;
        
        private long idPersonField;
        
        private bool idPersonFieldSpecified;
        
        private string last_nameField;
        
        private System.Nullable<System.DateTime> last_updateField;
        
        private bool last_updateFieldSpecified;
        
        private string passwordField;
        
        private byte[] pictureField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public forumPostDTO[] forumPosts {
            get {
                return this.forumPostsField;
            }
            set {
                this.forumPostsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public forumVoteDTO[] forumVotes {
            get {
                return this.forumVotesField;
            }
            set {
                this.forumVotesField = value;
            }
        }
        
        /// <remarks/>
        public long idPerson {
            get {
                return this.idPersonField;
            }
            set {
                this.idPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonSpecified {
            get {
                return this.idPersonFieldSpecified;
            }
            set {
                this.idPersonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> last_update {
            get {
                return this.last_updateField;
            }
            set {
                this.last_updateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool last_updateSpecified {
            get {
                return this.last_updateFieldSpecified;
            }
            set {
                this.last_updateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SeaceWCF.Dtos")]
    public partial class forumPostDTO {
        
        private string content_forumField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private forumPostDTO forumPost1Field;
        
        private forumPostDTO[] forumPosts1Field;
        
        private forumSubcategoryDTO forumSubcategoryField;
        
        private forumVoteDTO[] forumVotesField;
        
        private long idForumPostField;
        
        private bool idForumPostFieldSpecified;
        
        private System.Nullable<long> idPersonField;
        
        private bool idPersonFieldSpecified;
        
        private System.Nullable<long> idSubcategoryField;
        
        private bool idSubcategoryFieldSpecified;
        
        private string ipField;
        
        private System.Nullable<long> parent_postField;
        
        private bool parent_postFieldSpecified;
        
        private personDTO personField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string content_forum {
            get {
                return this.content_forumField;
            }
            set {
                this.content_forumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public forumPostDTO forumPost1 {
            get {
                return this.forumPost1Field;
            }
            set {
                this.forumPost1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public forumPostDTO[] forumPosts1 {
            get {
                return this.forumPosts1Field;
            }
            set {
                this.forumPosts1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public forumSubcategoryDTO forumSubcategory {
            get {
                return this.forumSubcategoryField;
            }
            set {
                this.forumSubcategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public forumVoteDTO[] forumVotes {
            get {
                return this.forumVotesField;
            }
            set {
                this.forumVotesField = value;
            }
        }
        
        /// <remarks/>
        public long idForumPost {
            get {
                return this.idForumPostField;
            }
            set {
                this.idForumPostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idForumPostSpecified {
            get {
                return this.idForumPostFieldSpecified;
            }
            set {
                this.idForumPostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> idPerson {
            get {
                return this.idPersonField;
            }
            set {
                this.idPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonSpecified {
            get {
                return this.idPersonFieldSpecified;
            }
            set {
                this.idPersonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> idSubcategory {
            get {
                return this.idSubcategoryField;
            }
            set {
                this.idSubcategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSubcategorySpecified {
            get {
                return this.idSubcategoryFieldSpecified;
            }
            set {
                this.idSubcategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> parent_post {
            get {
                return this.parent_postField;
            }
            set {
                this.parent_postField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parent_postSpecified {
            get {
                return this.parent_postFieldSpecified;
            }
            set {
                this.parent_postFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public personDTO person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SeaceWCF.Dtos")]
    public partial class forumSubcategoryDTO {
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string descriptionField;
        
        private forumCategoryDTO forumCategoryField;
        
        private forumPostDTO[] forumPostsField;
        
        private System.Nullable<long> idCategoryField;
        
        private bool idCategoryFieldSpecified;
        
        private long idSubcategoryField;
        
        private bool idSubcategoryFieldSpecified;
        
        private string ipField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public forumCategoryDTO forumCategory {
            get {
                return this.forumCategoryField;
            }
            set {
                this.forumCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public forumPostDTO[] forumPosts {
            get {
                return this.forumPostsField;
            }
            set {
                this.forumPostsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> idCategory {
            get {
                return this.idCategoryField;
            }
            set {
                this.idCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCategorySpecified {
            get {
                return this.idCategoryFieldSpecified;
            }
            set {
                this.idCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long idSubcategory {
            get {
                return this.idSubcategoryField;
            }
            set {
                this.idSubcategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSubcategorySpecified {
            get {
                return this.idSubcategoryFieldSpecified;
            }
            set {
                this.idSubcategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SeaceWCF.Dtos")]
    public partial class forumCategoryDTO {
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string descriptionField;
        
        private forumSubcategoryDTO[] forumSubcategoriesField;
        
        private long idCategoryField;
        
        private bool idCategoryFieldSpecified;
        
        private string ipField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public forumSubcategoryDTO[] forumSubcategories {
            get {
                return this.forumSubcategoriesField;
            }
            set {
                this.forumSubcategoriesField = value;
            }
        }
        
        /// <remarks/>
        public long idCategory {
            get {
                return this.idCategoryField;
            }
            set {
                this.idCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCategorySpecified {
            get {
                return this.idCategoryFieldSpecified;
            }
            set {
                this.idCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SeaceWCF.Dtos")]
    public partial class forumVoteDTO {
        
        private string commentField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private forumPostDTO forumPostField;
        
        private System.Nullable<long> idForumPostField;
        
        private bool idForumPostFieldSpecified;
        
        private System.Nullable<long> idPersonField;
        
        private bool idPersonFieldSpecified;
        
        private long idVoteField;
        
        private bool idVoteFieldSpecified;
        
        private string ipField;
        
        private personDTO personField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public forumPostDTO forumPost {
            get {
                return this.forumPostField;
            }
            set {
                this.forumPostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> idForumPost {
            get {
                return this.idForumPostField;
            }
            set {
                this.idForumPostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idForumPostSpecified {
            get {
                return this.idForumPostFieldSpecified;
            }
            set {
                this.idForumPostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> idPerson {
            get {
                return this.idPersonField;
            }
            set {
                this.idPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonSpecified {
            get {
                return this.idPersonFieldSpecified;
            }
            set {
                this.idPersonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long idVote {
            get {
                return this.idVoteField;
            }
            set {
                this.idVoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idVoteSpecified {
            get {
                return this.idVoteFieldSpecified;
            }
            set {
                this.idVoteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public personDTO person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void InsertarPersonaCompletedEventHandler(object sender, InsertarPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long InsertarPersonaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool InsertarPersonaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ActualizarPersonaCompletedEventHandler(object sender, ActualizarPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool ActualizarPersonaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ActualizarPersonaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EliminarPersonaCompletedEventHandler(object sender, EliminarPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool EliminarPersonaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool EliminarPersonaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ListarPersonaXnombreCompletedEventHandler(object sender, ListarPersonaXnombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPersonaXnombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPersonaXnombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public personDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((personDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ListarPersonasCompletedEventHandler(object sender, ListarPersonasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPersonasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPersonasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public personDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((personDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void BuscarPersonaPorIDCompletedEventHandler(object sender, BuscarPersonaPorIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarPersonaPorIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarPersonaPorIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public personDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((personDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void VerificarPasswordCompletedEventHandler(object sender, VerificarPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool VerificarPasswordResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool VerificarPasswordResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591