//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/10/20 - 23:37:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SeaceWCF.Dtos
{
    [DataContract()]
    public partial class forumSubcategoryDTO
    {
        [DataMember()]
        public Int64 idSubcategory { get; set; }

        [DataMember()]
        public Nullable<Int64> idCategory { get; set; }

        [DataMember()]
        public String title { get; set; }

        [DataMember()]
        public String description { get; set; }

        [DataMember()]
        public Nullable<DateTime> date { get; set; }

        [DataMember()]
        public String ip { get; set; }

        [DataMember()]
        public forumCategoryDTO forumCategory { get; set; }

        [DataMember()]
        public List<forumPostDTO> forumPosts { get; set; }

        public forumSubcategoryDTO()
        {
        }

        public forumSubcategoryDTO(Int64 idSubcategory, Nullable<Int64> idCategory, String title, String description, Nullable<DateTime> date, String ip, forumCategoryDTO forumCategory, List<forumPostDTO> forumPosts)
        {
			this.idSubcategory = idSubcategory;
			this.idCategory = idCategory;
			this.title = title;
			this.description = description;
			this.date = date;
			this.ip = ip;
			this.forumCategory = forumCategory;
			this.forumPosts = forumPosts;
        }
    }
}
