//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/10/20 - 22:53:29
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SeaceWCF.Dtos
{
    [DataContract()]
    public partial class forumPostDTO
    {
        [DataMember()]
        public Int64 idForumPost { get; set; }

        [DataMember()]
        public Nullable<Int64> idSubcategory { get; set; }

        [DataMember()]
        public Nullable<Int64> idPerson { get; set; }

        [DataMember()]
        public Nullable<Int64> parent_post { get; set; }

        [DataMember()]
        public String title { get; set; }

        [DataMember()]
        public String content_forum { get; set; }

        [DataMember()]
        public Nullable<DateTime> date { get; set; }

        [DataMember()]
        public String ip { get; set; }

        [DataMember()]
        public List<Int64> forumPosts1_idForumPost { get; set; }

        [DataMember()]
        public Int64 forumPost1_idForumPost { get; set; }

        [DataMember()]
        public Int64 forumSubcategory_idSubcategory { get; set; }

        [DataMember()]
        public Int64 person_idPerson { get; set; }

        [DataMember()]
        public List<Int64> forumVotes_idVote { get; set; }

        public forumPostDTO()
        {
        }

        public forumPostDTO(Int64 idForumPost, Nullable<Int64> idSubcategory, Nullable<Int64> idPerson, Nullable<Int64> parent_post, String title, String content_forum, Nullable<DateTime> date, String ip, List<Int64> forumPosts1_idForumPost, Int64 forumPost1_idForumPost, Int64 forumSubcategory_idSubcategory, Int64 person_idPerson, List<Int64> forumVotes_idVote)
        {
			this.idForumPost = idForumPost;
			this.idSubcategory = idSubcategory;
			this.idPerson = idPerson;
			this.parent_post = parent_post;
			this.title = title;
			this.content_forum = content_forum;
			this.date = date;
			this.ip = ip;
			this.forumPosts1_idForumPost = forumPosts1_idForumPost;
			this.forumPost1_idForumPost = forumPost1_idForumPost;
			this.forumSubcategory_idSubcategory = forumSubcategory_idSubcategory;
			this.person_idPerson = person_idPerson;
			this.forumVotes_idVote = forumVotes_idVote;
        }
    }
}
