//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/10/20 - 23:37:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SeaceWCF.Dtos
{
    [DataContract()]
    public partial class forumCategoryDTO
    {
        [DataMember()]
        public Int64 idCategory { get; set; }

        [DataMember()]
        public String title { get; set; }

        [DataMember()]
        public String description { get; set; }

        [DataMember()]
        public Nullable<DateTime> date { get; set; }

        [DataMember()]
        public String ip { get; set; }

        [DataMember()]
        public List<forumSubcategoryDTO> forumSubcategories { get; set; }

        public forumCategoryDTO()
        {
        }

        public forumCategoryDTO(Int64 idCategory, String title, String description, Nullable<DateTime> date, String ip, List<forumSubcategoryDTO> forumSubcategories)
        {
			this.idCategory = idCategory;
			this.title = title;
			this.description = description;
			this.date = date;
			this.ip = ip;
			this.forumSubcategories = forumSubcategories;
        }
    }
}
