//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/10/20 - 23:37:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SeaceWCF.Dtos
{
    [DataContract()]
    public partial class personDTO
    {
        [DataMember()]
        public Int64 idPerson { get; set; }

        [DataMember()]
        public String first_name { get; set; }

        [DataMember()]
        public String last_name { get; set; }

        [DataMember()]
        public Byte[] picture { get; set; }

        [DataMember()]
        public String email { get; set; }

        [DataMember()]
        public Nullable<Boolean> active { get; set; }

        [DataMember()]
        public String username { get; set; }

        [DataMember()]
        public String password { get; set; }

        [DataMember()]
        public Nullable<DateTime> last_update { get; set; }

        [DataMember()]
        public List<forumPostDTO> forumPosts { get; set; }

        [DataMember()]
        public List<forumVoteDTO> forumVotes { get; set; }

        public personDTO()
        {
        }

        public personDTO(Int64 idPerson, String first_name, String last_name, Byte[] picture, String email, Nullable<Boolean> active, String username, String password, Nullable<DateTime> last_update, List<forumPostDTO> forumPosts, List<forumVoteDTO> forumVotes)
        {
			this.idPerson = idPerson;
			this.first_name = first_name;
			this.last_name = last_name;
			this.picture = picture;
			this.email = email;
			this.active = active;
			this.username = username;
			this.password = password;
			this.last_update = last_update;
			this.forumPosts = forumPosts;
			this.forumVotes = forumVotes;
        }
    }
}
