//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/10/20 - 23:37:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SeaceWCF.Dtos;
using SeaceWCF;

namespace SeaceWCF.Assembler
{

    /// <summary>
    /// Assembler for <see cref="forumVote"/> and <see cref="forumVoteDTO"/>.
    /// </summary>
    public static partial class forumVoteAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="forumVoteDTO"/> converted from <see cref="forumVote"/>.</param>
        static partial void OnDTO(this forumVote entity, forumVoteDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="forumVote"/> converted from <see cref="forumVoteDTO"/>.</param>
        static partial void OnEntity(this forumVoteDTO dto, forumVote entity);

        /// <summary>
        /// Converts this instance of <see cref="forumVoteDTO"/> to an instance of <see cref="forumVote"/>.
        /// </summary>
        /// <param name="dto"><see cref="forumVoteDTO"/> to convert.</param>
        public static forumVote ToEntity(this forumVoteDTO dto)
        {
            if (dto == null) return null;

            var entity = new forumVote();

            entity.idVote = dto.idVote;
            entity.idForumPost = dto.idForumPost;
            entity.idPerson = dto.idPerson;
            entity.date = dto.date;
            entity.comment = dto.comment;
            entity.ip = dto.ip;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="forumVote"/> to an instance of <see cref="forumVoteDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="forumVote"/> to convert.</param>
        public static forumVoteDTO ToDTO(this forumVote entity)
        {
            if (entity == null) return null;

            var dto = new forumVoteDTO();

            dto.idVote = entity.idVote;
            dto.idForumPost = entity.idForumPost;
            dto.idPerson = entity.idPerson;
            dto.date = entity.date;
            dto.comment = entity.comment;
            dto.ip = entity.ip;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="forumVoteDTO"/> to an instance of <see cref="forumVote"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<forumVote> ToEntities(this IEnumerable<forumVoteDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="forumVote"/> to an instance of <see cref="forumVoteDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<forumVoteDTO> ToDTOs(this IEnumerable<forumVote> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
